set(quiche_sources
	${PROJECT_SOURCE_DIR}/quiche/common/capsule.cc
	${PROJECT_SOURCE_DIR}/quiche/common/http/http_header_block.cc
	${PROJECT_SOURCE_DIR}/quiche/common/http/http_header_storage.cc
	${PROJECT_SOURCE_DIR}/quiche/common/masque/connect_ip_datagram_payload.cc
	${PROJECT_SOURCE_DIR}/quiche/common/masque/connect_udp_datagram_payload.cc
	${PROJECT_SOURCE_DIR}/quiche/common/platform/api/quiche_file_utils.cc
	${PROJECT_SOURCE_DIR}/quiche/common/platform/api/quiche_hostname_utils.cc
	${PROJECT_SOURCE_DIR}/quiche/common/platform/default/quiche_platform_impl/quiche_command_line_flags_impl.cc
	${PROJECT_SOURCE_DIR}/quiche/common/platform/default/quiche_platform_impl/quiche_default_proof_providers_impl.cc
	${PROJECT_SOURCE_DIR}/quiche/common/platform/default/quiche_platform_impl/quiche_file_utils_impl.cc
	${PROJECT_SOURCE_DIR}/quiche/common/platform/default/quiche_platform_impl/quiche_flags_impl.cc
	${PROJECT_SOURCE_DIR}/quiche/common/platform/default/quiche_platform_impl/quiche_logging_impl.cc
	${PROJECT_SOURCE_DIR}/quiche/common/platform/default/quiche_platform_impl/quiche_stack_trace_impl.cc
	${PROJECT_SOURCE_DIR}/quiche/common/platform/default/quiche_platform_impl/quiche_time_utils_impl.cc
	${PROJECT_SOURCE_DIR}/quiche/common/platform/default/quiche_platform_impl/quiche_url_utils_impl.cc
	${PROJECT_SOURCE_DIR}/quiche/common/quiche_buffer_allocator.cc
	${PROJECT_SOURCE_DIR}/quiche/common/quiche_crypto_logging.cc
	${PROJECT_SOURCE_DIR}/quiche/common/quiche_data_reader.cc
	${PROJECT_SOURCE_DIR}/quiche/common/quiche_data_writer.cc
	${PROJECT_SOURCE_DIR}/quiche/common/quiche_ip_address.cc
	${PROJECT_SOURCE_DIR}/quiche/common/quiche_ip_address_family.cc
	${PROJECT_SOURCE_DIR}/quiche/common/quiche_mem_slice_storage.cc
	${PROJECT_SOURCE_DIR}/quiche/common/quiche_random.cc
	${PROJECT_SOURCE_DIR}/quiche/common/quiche_simple_arena.cc
	${PROJECT_SOURCE_DIR}/quiche/common/quiche_socket_address.cc
	${PROJECT_SOURCE_DIR}/quiche/common/quiche_text_utils.cc
	${PROJECT_SOURCE_DIR}/quiche/common/simple_buffer_allocator.cc
	${PROJECT_SOURCE_DIR}/quiche/common/structured_headers.cc
	${PROJECT_SOURCE_DIR}/quiche/common/vectorized_io_utils.cc
	${PROJECT_SOURCE_DIR}/quiche/http2/adapter/header_validator.cc
	${PROJECT_SOURCE_DIR}/quiche/http2/core/http2_constants.cc
	${PROJECT_SOURCE_DIR}/quiche/http2/core/http2_frame_decoder_adapter.cc
	${PROJECT_SOURCE_DIR}/quiche/http2/core/http2_structures.cc
	${PROJECT_SOURCE_DIR}/quiche/http2/core/spdy_alt_svc_wire_format.cc
	${PROJECT_SOURCE_DIR}/quiche/http2/core/spdy_frame_builder.cc
	${PROJECT_SOURCE_DIR}/quiche/http2/core/spdy_framer.cc
	${PROJECT_SOURCE_DIR}/quiche/http2/core/spdy_protocol.cc
	${PROJECT_SOURCE_DIR}/quiche/http2/decoder/decode_buffer.cc
	${PROJECT_SOURCE_DIR}/quiche/http2/decoder/decode_http2_structures.cc
	${PROJECT_SOURCE_DIR}/quiche/http2/decoder/decode_status.cc
	${PROJECT_SOURCE_DIR}/quiche/http2/decoder/frame_decoder_state.cc
	${PROJECT_SOURCE_DIR}/quiche/http2/decoder/http2_frame_decoder.cc
	${PROJECT_SOURCE_DIR}/quiche/http2/decoder/http2_frame_decoder_listener.cc
	${PROJECT_SOURCE_DIR}/quiche/http2/decoder/http2_structure_decoder.cc
	${PROJECT_SOURCE_DIR}/quiche/http2/decoder/payload_decoders/altsvc_payload_decoder.cc
	${PROJECT_SOURCE_DIR}/quiche/http2/decoder/payload_decoders/continuation_payload_decoder.cc
	${PROJECT_SOURCE_DIR}/quiche/http2/decoder/payload_decoders/data_payload_decoder.cc
	${PROJECT_SOURCE_DIR}/quiche/http2/decoder/payload_decoders/goaway_payload_decoder.cc
	${PROJECT_SOURCE_DIR}/quiche/http2/decoder/payload_decoders/headers_payload_decoder.cc
	${PROJECT_SOURCE_DIR}/quiche/http2/decoder/payload_decoders/ping_payload_decoder.cc
	${PROJECT_SOURCE_DIR}/quiche/http2/decoder/payload_decoders/priority_payload_decoder.cc
	${PROJECT_SOURCE_DIR}/quiche/http2/decoder/payload_decoders/priority_update_payload_decoder.cc
	${PROJECT_SOURCE_DIR}/quiche/http2/decoder/payload_decoders/push_promise_payload_decoder.cc
	${PROJECT_SOURCE_DIR}/quiche/http2/decoder/payload_decoders/rst_stream_payload_decoder.cc
	${PROJECT_SOURCE_DIR}/quiche/http2/decoder/payload_decoders/settings_payload_decoder.cc
	${PROJECT_SOURCE_DIR}/quiche/http2/decoder/payload_decoders/unknown_payload_decoder.cc
	${PROJECT_SOURCE_DIR}/quiche/http2/decoder/payload_decoders/window_update_payload_decoder.cc
	${PROJECT_SOURCE_DIR}/quiche/http2/hpack/decoder/hpack_block_decoder.cc
	${PROJECT_SOURCE_DIR}/quiche/http2/hpack/decoder/hpack_decoder.cc
	${PROJECT_SOURCE_DIR}/quiche/http2/hpack/decoder/hpack_decoder_listener.cc
	${PROJECT_SOURCE_DIR}/quiche/http2/hpack/decoder/hpack_decoder_state.cc
	${PROJECT_SOURCE_DIR}/quiche/http2/hpack/decoder/hpack_decoder_string_buffer.cc
	${PROJECT_SOURCE_DIR}/quiche/http2/hpack/decoder/hpack_decoder_tables.cc
	${PROJECT_SOURCE_DIR}/quiche/http2/hpack/decoder/hpack_decoding_error.cc
	${PROJECT_SOURCE_DIR}/quiche/http2/hpack/decoder/hpack_entry_decoder.cc
	${PROJECT_SOURCE_DIR}/quiche/http2/hpack/decoder/hpack_entry_decoder_listener.cc
	${PROJECT_SOURCE_DIR}/quiche/http2/hpack/decoder/hpack_entry_type_decoder.cc
	${PROJECT_SOURCE_DIR}/quiche/http2/hpack/decoder/hpack_string_decoder.cc
	${PROJECT_SOURCE_DIR}/quiche/http2/hpack/decoder/hpack_whole_entry_buffer.cc
	${PROJECT_SOURCE_DIR}/quiche/http2/hpack/decoder/hpack_whole_entry_listener.cc
	${PROJECT_SOURCE_DIR}/quiche/http2/hpack/hpack_constants.cc
	${PROJECT_SOURCE_DIR}/quiche/http2/hpack/hpack_decoder_adapter.cc
	${PROJECT_SOURCE_DIR}/quiche/http2/hpack/hpack_encoder.cc
	${PROJECT_SOURCE_DIR}/quiche/http2/hpack/hpack_entry.cc
	${PROJECT_SOURCE_DIR}/quiche/http2/hpack/hpack_header_table.cc
	${PROJECT_SOURCE_DIR}/quiche/http2/hpack/hpack_output_stream.cc
	${PROJECT_SOURCE_DIR}/quiche/http2/hpack/hpack_static_table.cc
	${PROJECT_SOURCE_DIR}/quiche/http2/hpack/http2_hpack_constants.cc
	${PROJECT_SOURCE_DIR}/quiche/http2/hpack/huffman/hpack_huffman_decoder.cc
	${PROJECT_SOURCE_DIR}/quiche/http2/hpack/huffman/hpack_huffman_encoder.cc
	${PROJECT_SOURCE_DIR}/quiche/http2/hpack/huffman/huffman_spec_tables.cc
	${PROJECT_SOURCE_DIR}/quiche/http2/hpack/varint/hpack_varint_decoder.cc
	${PROJECT_SOURCE_DIR}/quiche/http2/hpack/varint/hpack_varint_encoder.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/chlo_extractor.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/congestion_control/bandwidth_sampler.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/congestion_control/bbr2_drain.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/congestion_control/bbr2_misc.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/congestion_control/bbr2_probe_bw.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/congestion_control/bbr2_probe_rtt.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/congestion_control/bbr2_sender.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/congestion_control/bbr2_startup.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/congestion_control/bbr_sender.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/congestion_control/cubic_bytes.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/congestion_control/general_loss_algorithm.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/congestion_control/hybrid_slow_start.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/congestion_control/pacing_sender.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/congestion_control/prague_sender.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/congestion_control/prr_sender.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/congestion_control/rtt_stats.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/congestion_control/send_algorithm_interface.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/congestion_control/tcp_cubic_sender_bytes.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/congestion_control/uber_loss_algorithm.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/crypto/aead_base_decrypter.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/crypto/aead_base_encrypter.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/crypto/aes_128_gcm_12_decrypter.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/crypto/aes_128_gcm_12_encrypter.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/crypto/aes_128_gcm_decrypter.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/crypto/aes_128_gcm_encrypter.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/crypto/aes_256_gcm_decrypter.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/crypto/aes_256_gcm_encrypter.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/crypto/aes_base_decrypter.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/crypto/aes_base_encrypter.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/crypto/cert_compressor.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/crypto/certificate_view.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/crypto/chacha20_poly1305_decrypter.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/crypto/chacha20_poly1305_encrypter.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/crypto/chacha20_poly1305_tls_decrypter.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/crypto/chacha20_poly1305_tls_encrypter.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/crypto/chacha_base_decrypter.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/crypto/chacha_base_encrypter.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/crypto/channel_id.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/crypto/client_proof_source.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/crypto/crypto_framer.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/crypto/crypto_handshake.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/crypto/crypto_handshake_message.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/crypto/crypto_secret_boxer.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/crypto/crypto_utils.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/crypto/curve25519_key_exchange.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/crypto/key_exchange.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/crypto/null_decrypter.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/crypto/null_encrypter.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/crypto/p256_key_exchange.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/crypto/proof_source.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/crypto/proof_source_x509.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/crypto/quic_client_session_cache.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/crypto/quic_compressed_certs_cache.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/crypto/quic_crypter.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/crypto/quic_crypto_client_config.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/crypto/quic_crypto_proof.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/crypto/quic_crypto_server_config.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/crypto/quic_decrypter.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/crypto/quic_encrypter.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/crypto/quic_hkdf.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/crypto/tls_client_connection.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/crypto/tls_connection.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/crypto/tls_server_connection.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/crypto/transport_parameters.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/deterministic_connection_id_generator.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/frames/quic_ack_frame.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/frames/quic_ack_frequency_frame.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/frames/quic_blocked_frame.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/frames/quic_connection_close_frame.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/frames/quic_crypto_frame.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/frames/quic_frame.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/frames/quic_goaway_frame.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/frames/quic_handshake_done_frame.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/frames/quic_immediate_ack_frame.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/frames/quic_max_streams_frame.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/frames/quic_message_frame.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/frames/quic_new_connection_id_frame.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/frames/quic_new_token_frame.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/frames/quic_padding_frame.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/frames/quic_path_challenge_frame.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/frames/quic_path_response_frame.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/frames/quic_ping_frame.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/frames/quic_reset_stream_at_frame.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/frames/quic_retire_connection_id_frame.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/frames/quic_rst_stream_frame.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/frames/quic_stop_sending_frame.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/frames/quic_stop_waiting_frame.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/frames/quic_stream_frame.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/frames/quic_streams_blocked_frame.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/frames/quic_window_update_frame.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/http/http_constants.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/http/http_decoder.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/http/http_encoder.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/http/metadata_decoder.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/http/quic_header_list.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/http/quic_headers_stream.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/http/quic_receive_control_stream.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/http/quic_send_control_stream.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/http/quic_server_initiated_spdy_stream.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/http/quic_server_session_base.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/http/quic_spdy_client_session_base.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/http/quic_spdy_client_session.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/http/quic_spdy_client_stream.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/http/quic_spdy_server_stream_base.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/http/quic_spdy_session.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/http/quic_spdy_stream_body_manager.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/http/quic_spdy_stream.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/http/spdy_utils.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/http/web_transport_http3.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/http/web_transport_stream_adapter.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/io/event_loop_connecting_client_socket.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/io/event_loop_socket_factory.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/io/quic_default_event_loop.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/io/quic_poll_event_loop.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/io/socket.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/legacy_quic_stream_id_manager.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/qpack/new_qpack_blocking_manager.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/qpack/qpack_decoded_headers_accumulator.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/qpack/qpack_decoder.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/qpack/qpack_decoder_stream_receiver.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/qpack/qpack_decoder_stream_sender.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/qpack/qpack_encoder.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/qpack/qpack_encoder_stream_receiver.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/qpack/qpack_encoder_stream_sender.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/qpack/qpack_header_table.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/qpack/qpack_index_conversions.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/qpack/qpack_instruction_decoder.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/qpack/qpack_instruction_encoder.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/qpack/qpack_instructions.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/qpack/qpack_progressive_decoder.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/qpack/qpack_receive_stream.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/qpack/qpack_required_insert_count.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/qpack/qpack_send_stream.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/qpack/qpack_static_table.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/qpack/value_splitting_header_list.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_ack_listener_interface.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_alarm.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_bandwidth.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_blocked_writer_list.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_buffered_packet_store.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_chaos_protector.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_coalesced_packet.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_config.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_connection_alarms.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_connection.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_connection_context.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_connection_id.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_connection_id_manager.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_connection_stats.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_constants.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_control_frame_manager.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_crypto_client_handshaker.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_crypto_client_stream.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_crypto_handshaker.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_crypto_server_stream_base.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_crypto_server_stream.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_crypto_stream.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_datagram_queue.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_data_reader.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_data_writer.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_default_clock.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_default_packet_writer.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_dispatcher.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_dispatcher_stats.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_error_codes.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_flow_controller.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_framer.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_idle_network_detector.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_mtu_discovery.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_network_blackhole_detector.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_packet_creator.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_packet_number.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_packet_reader.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_packets.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_path_validator.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_ping_manager.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_queue_alarm_factory.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_received_packet_manager.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_sent_packet_manager.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_server_id.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_session.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_socket_address_coder.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_stream.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_stream_id_manager.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_stream_priority.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_stream_send_buffer.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_stream_sequencer_buffer.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_stream_sequencer.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_sustained_bandwidth_recorder.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_tag.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_time.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_time_wait_list_manager.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_transmission_info.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_types.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_udp_socket.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_unacked_packet_map.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_utils.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_version_manager.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_versions.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/quic_write_blocked_list.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/tls_chlo_extractor.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/tls_client_handshaker.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/tls_handshaker.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/tls_server_handshaker.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/uber_quic_stream_id_manager.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/uber_received_packet_manager.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/web_transport_stats.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/core/web_transport_write_blocked_list.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/tools/connect_server_backend.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/tools/connect_tunnel.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/tools/connect_udp_tunnel.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/tools/quic_client_base.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/tools/quic_client_default_network_helper.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/tools/quic_default_client.cc
	${PROJECT_SOURCE_DIR}/quiche/quic/tools/quic_name_lookup.cc
	${PROJECT_SOURCE_DIR}/quiche/web_transport/complete_buffer_visitor.cc
)